export const translations = {
    ro: {
        title: "Casa de Productie Filme",
        movies: "Filme", actors: "Actori", stats: "Statistici", users: "Utilizatori",
        directors: "Regizori", screenwriters: "Scenaristi", producers: "Producatori",
        add: "Adauga", save: "Salveaza", edit: "Editeaza", delete: "Sterge", search: "Cauta",
        filter: "Filtreaza", export: "Exporta", notify: "Notifica",
        titleField: "Titlu", descField: "Descriere", yearField: "An Realizare",
        typeField: "Tip Film", categoryField: "Categorie", rating: "Top Rating",
        views: "Top Vizualizari", images: "Imagini Film",
        unauthorized: "Nu aveti permisiunea de a accesa aceasta sectiune!",
        searchPlaceholder: "Cauta dupa titlu...", searchActorPlaceholder: "Cauta actor dupa nume...",
        filterByType: "Filtreaza dupa tip", filterByCategory: "Filtreaza dupa categorie",
        filterByYear: "Filtreaza dupa an", allTypes: "Toate tipurile",
        allCategories: "Toate categoriile", notifMessage: "Mesaj notificare",
        notifUserId: "ID Utilizator", send: "Trimite", close: "Inchide",
        filmImages: "Imagini Film", addImage: "Adauga Imagine URL",
        userType: "Tip utilizator", email: "Email", phone: "Telefon",
        statistics: "Statistici", graphStats: "Statistici Grafice",
        catalogTeam: "Catalog echipa film",
        catalogHint: "Adauga regizori, scenaristi, producatori si actori pentru filme.",
        reset: "Reset", exportCsv: "Export CSV", details: "Detalii",
        adminUsers: "Administrare Utilizatori", addUser: "Adauga Utilizator",
        sendNotif: "Trimite Notificare", password: "Parola", actions: "Actiuni",
        producer: "Producator", distribution: "Distributie", nationality: "Nationalitate",
        birthYear: "An nastere", company: "Companie", photoUrl: "URL Foto"
    },
    en: {
        title: "Movie Production House",
        movies: "Movies", actors: "Actors", stats: "Statistics", users: "Users",
        directors: "Directors", screenwriters: "Screenwriters", producers: "Producers",
        add: "Add", save: "Save", edit: "Edit", delete: "Delete", search: "Search",
        filter: "Filter", export: "Export", notify: "Notify",
        titleField: "Title", descField: "Description", yearField: "Release Year",
        typeField: "Film Type", categoryField: "Category", rating: "Top Rated",
        views: "Top Views", images: "Film Images",
        unauthorized: "You do not have permission to access this section!",
        searchPlaceholder: "Search by title...", searchActorPlaceholder: "Search actor by name...",
        filterByType: "Filter by type", filterByCategory: "Filter by category",
        filterByYear: "Filter by year", allTypes: "All types",
        allCategories: "All categories", notifMessage: "Notification message",
        notifUserId: "User ID", send: "Send", close: "Close",
        filmImages: "Film Images", addImage: "Add Image URL",
        userType: "User type", email: "Email", phone: "Phone",
        statistics: "Statistics", graphStats: "Graph Statistics",
        catalogTeam: "Film team catalog",
        catalogHint: "Add directors, screenwriters, producers and actors for movies.",
        reset: "Reset", exportCsv: "Export CSV", details: "Details",
        adminUsers: "User administration", addUser: "Add user", sendNotif: "Send notification",
        password: "Password", actions: "Actions", producer: "Producer",
        distribution: "Cast", nationality: "Nationality", birthYear: "Birth year",
        company: "Company", photoUrl: "Photo URL"
    },
    fr: {
        title: "Maison de Production de Films",
        movies: "Films", actors: "Acteurs", stats: "Statistiques", users: "Utilisateurs",
        directors: "Realisateurs", screenwriters: "Scenaristes", producers: "Producteurs",
        add: "Ajouter", save: "Enregistrer", edit: "Modifier", delete: "Supprimer", search: "Rechercher",
        filter: "Filtrer", export: "Exporter", notify: "Notifier",
        titleField: "Titre", descField: "Description", yearField: "Annee de realisation",
        typeField: "Type de film", categoryField: "Categorie", rating: "Top Evalue",
        views: "Top Vues", images: "Images du film",
        unauthorized: "Vous n'etes pas autorise a acceder a cette section!",
        searchPlaceholder: "Rechercher par titre...", searchActorPlaceholder: "Rechercher acteur par nom...",
        filterByType: "Filtrer par type", filterByCategory: "Filtrer par categorie",
        filterByYear: "Filtrer par annee", allTypes: "Tous les types",
        allCategories: "Toutes les categories", notifMessage: "Message de notification",
        notifUserId: "ID Utilisateur", send: "Envoyer", close: "Fermer",
        filmImages: "Images du film", addImage: "Ajouter URL image",
        userType: "Type d'utilisateur", email: "E-mail", phone: "Telephone",
        statistics: "Statistiques", graphStats: "Statistiques graphiques",
        catalogTeam: "Catalogue equipe film",
        catalogHint: "Ajoutez realisateurs, scenaristes, producteurs et acteurs.",
        reset: "Reinitialiser", exportCsv: "Export CSV", details: "Details",
        adminUsers: "Administration utilisateurs", addUser: "Ajouter utilisateur",
        sendNotif: "Envoyer notification", password: "Mot de passe", actions: "Actions",
        producer: "Producteur", distribution: "Distribution", nationality: "Nationalite",
        birthYear: "Annee naissance", company: "Societe", photoUrl: "URL photo"
    }
};
